In [14]:
import pandas as pd

In [15]:
data = pd.read_csv('data/bitcoin2.csv')
data

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,2106399049926488369,2026-10-03T15:00:43.000Z,0,Cathie Wood says smart investors need to start...,2106399049926488369,NaN,NaN,en,NaN,0,0,0,https://x.com/cryptofusedaily/status/210639904...,1481321492247977989,cryptofusedaily
1,2106367658392518952,2026-10-03T15:00:42.000Z,0,@Arpon_360 @mdv_btc Bitcoin block growth gives...,2106399046651011234,NaN,Arpon_360,en,NaN,0,0,0,https://x.com/HabibPaart44952/status/210639904...,1638581352797749251,HabibPaart44952
2,2106396853373976731,2026-10-03T15:00:40.000Z,1,"@MDCTrades305 Yeah, this trend has been going ...",2106399037746225470,NaN,MDCTrades305,en,NaN,0,0,0,https://x.com/just_stevin/status/2106399037746...,806684285499572225,just_stevin
3,2106399027621241008,2026-10-03T15:00:37.000Z,0,You can go back in time and meet your 2010 sel...,2106399027621241008,NaN,NaN,en,NaN,0,0,0,https://x.com/Thebitcoinway_/status/2106399027...,1472210381221289987,Thebitcoinway_
4,2106399001268625917,2026-10-03T15:00:31.000Z,1,“FIAT SUPPLY CAN EXPAND.\nBITCOIN SUPPLY CANNO...,2106399001268625917,https://pbs.twimg.com/media/HTtutKOboAAMF6F.jpg,NaN,en,NaN,0,0,0,https://x.com/BhomeshPanbqpf/status/2106399001...,2088577625036111872,BhomeshPanbqpf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,2106379383539720513,2026-10-03T14:13:29.000Z,1,@FuturesWire Soft jobs data (29K vs 90K expect...,2106387166469452136,NaN,FuturesWire,en,NaN,0,1,0,https://x.com/futuredotnews/status/21063871664...,1483695499442286592,futuredotnews
636,2106308563056414801,2026-10-03T14:13:23.000Z,0,@kisc_0 @vangrid_io There’s definitely somethi...,2106387139638296589,NaN,kisc_0,en,NaN,0,0,0,https://x.com/elijahnnaoma1/status/21063871396...,1594064468836851713,elijahnnaoma1
637,2106127684971766162,2026-10-03T14:13:20.000Z,0,@rodpalmerhodl there are around 100m fiat mill...,2106387127537971239,NaN,rodpalmerhodl,en,NaN,0,0,0,https://x.com/ob_hodl/status/2106387127537971239,973090717059964928,ob_hodl
638,2090834222189523406,2026-10-03T14:13:14.000Z,0,@davelund_ The fellowship will continue to gro...,2106387101629686109,NaN,davelund_,en,NaN,0,0,0,https://x.com/C97478318/status/210638710162968...,1508935844932952067,C97478318
639,2106387099524141058,2026-10-03T14:13:13.000Z,1,$KEEL turned bitcoin-mine power into AI data c...,2106387099524141058,NaN,NaN,en,NaN,0,0,0,https://x.com/SalesSenseii/status/210638709952...,1798068568992731136,SalesSenseii

In [16]:
import re
def cleaning(sent):
    #Mengubah kata menjadi huruf kecil semua dengan fungsi lower()
    string = sent.lower()
    string = re.sub(r'http\S+', '', string) #Menghapus URL
    string = re.sub(r'@\w+', '', string) #Menghapus mention
    string = re.sub(r'#\w+', '', string) #Menghapus hashtag
    string = re.sub(r'\d+', '', string) #Menghapus angka
    string = re.sub(r'[^\w\s]', '', string) #Menghapus karakter khusus
    return string

In [17]:
data['full_text'] = data.full_text.apply(cleaning)
data.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,2106399049926488369,2026-10-03T15:00:43.000Z,0,cathie wood says smart investors need to start...,2106399049926488369,NaN,NaN,en,NaN,0,0,0,https://x.com/cryptofusedaily/status/210639904...,1481321492247977989,cryptofusedaily
1,2106367658392518952,2026-10-03T15:00:42.000Z,0,bitcoin block growth gives the nft a living ...,2106399046651011234,NaN,Arpon_360,en,NaN,0,0,0,https://x.com/HabibPaart44952/status/210639904...,1638581352797749251,HabibPaart44952
2,2106396853373976731,2026-10-03T15:00:40.000Z,1,yeah this trend has been going on for a while...,2106399037746225470,NaN,MDCTrades305,en,NaN,0,0,0,https://x.com/just_stevin/status/2106399037746...,806684285499572225,just_stevin
3,2106399027621241008,2026-10-03T15:00:37.000Z,0,you can go back in time and meet your self\n\...,2106399027621241008,NaN,NaN,en,NaN,0,0,0,https://x.com/Thebitcoinway_/status/2106399027...,1472210381221289987,Thebitcoinway_
4,2106399001268625917,2026-10-03T15:00:31.000Z,1,fiat supply can expand\nbitcoin supply cannot\...,2106399001268625917,https://pbs.twimg.com/media/HTtutKOboAAMF6F.jpg,NaN,en,NaN,0,0,0,https://x.com/BhomeshPanbqpf/status/2106399001...,2088577625036111872,BhomeshPanbqpf

In [18]:
data = data[['full_text']]
data.head()

                                           full_text
0  cathie wood says smart investors need to start...
1    bitcoin block growth gives the nft a living ...
2   yeah this trend has been going on for a while...
3  you can go back in time and meet your  self\n\...
4  fiat supply can expand\nbitcoin supply cannot\...

In [19]:
data.to_csv('data/bitcoin2_clean.csv', index=False)